# Generated by Django 2.2 on 2021-08-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ssh_useradmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssh_ip', models.CharField(default='', max_length=20)),
                ('ssh_root', models.CharField(max_length=20)),
                ('ssh_passwd', models.CharField(max_length=50)),
                ('ssg_hostport', models.CharField(max_length=20)),
                ('ssh_host_cloud_merchant', models.CharField(max_length=50)),
                ('ssh_host_in_the_area', models.CharField(max_length=50)),
                ('ssh_host_status_code', models.CharField(default=0, max_length=50)),
                ('ssh_hsot_public_key', models.CharField(max_length=5200)),
                ('ssh_hsot_private_key', models.CharField(max_length=5200)),
                ('ssh_host_cpu', models.CharField(max_length=16)),
                ('ssh_host_Memory', models.CharField(max_length=16)),
                ('ssh_host_disk', models.CharField(max_length=16)),
                ('ssh_host_system', models.CharField(max_length=16)),
            ],
        ),
    ]
