# Generated by Django 2.2 on 2021-08-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='useradmin_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_level', models.CharField(max_length=20)),
                ('user_ip', models.CharField(default='', max_length=20)),
                ('user_passwd', models.CharField(max_length=50)),
                ('user_hostport', models.CharField(max_length=20)),
                ('user_area', models.CharField(max_length=50)),
                ('user_Merchant', models.CharField(max_length=50)),
                ('user_status', models.CharField(max_length=10)),
            ],
        ),
    ]
