# Generated by Django 2.2 on 2021-08-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_useradmin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssh_useradmin',
            name='ssh_host_system',
            field=models.CharField(max_length=50),
        ),
    ]
